---
title: "DMP"
author: "Javier Pena-Bastidas, *Mc Master University PhD student*"
date: "02/01/2022"
output: html_document
---

## Project Data Analysis

List the data that you expect to use, collect or create in your project. Identify if you are generating or collecting the data and if you are using existing datasets? 
(Colected = C, Existing= E)

1. Survey from WG1 | (C)
2. Land use datasets | (E)
3. 


Are there legal or ethicial restrictions that you will need to address?

Go through the Quick Hits for Data Management and identify possible strategies to build and protect the value of your data.

- Where will you keep raw data and how will you back it up?

- What file formats do you anticipate your data will be in? Are the formats open or can they be converted to open formats?

- Create a File naming convention for your project data

- What standards are relevant to your project? List any existing standards or best practices in use in your field or in your lab? This could include instrument procedures or file management standards. What standards might you want to create to help you manage your data?

- List possible strategies you might use to document your data throughout your project.